declare module '@synthetixio/synpress/helpers'
declare module '@synthetixio/synpress/commands/metamask'
declare module '@synthetixio/synpress/commands/playwright'
declare module '@synthetixio/synpress/commands/synpress'
declare module '@c0x12c/e2e-playwright/step'